version: 33
jobs:
- name: Push2Github
  steps:
  - !UseTemplateStep
    name: Push2Github
    templateName: Push2Github
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  - !TagCreateTrigger
    branches: main
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: PullFromGithub
  steps:
  - !PullRepository
    name: pullFromGithub
    remoteUrl: https://github.com/superwhys/superBlog
    passwordSecret: Publish2GIthub
    refs: refs/heads/* refs/tags/*
    withLfs: false
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !ScheduleTrigger
    cronExpression: 0 0 */2 * * ?
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: dockerBuild
  jobExecutor: dockerExecutor
  steps:
  - !CheckoutStep
    name: checkout code
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    cloneDepth: 1
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !BuildImageStep
    name: build image
    output: !RegistryOutput
      tags: '@server@/@project_path@/@project_name@:latest @server@/@project_path@/@project_name@:@file:version@'
    builtInRegistryAccessTokenSecret: repo-token
    platforms: linux/amd64
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !TagCreateTrigger
    tags: v\d+\.\d+\.\d+
    branches: main
    projects: superBlog
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
stepTemplates:
- name: Push2Github
  steps:
  - !PushRepository
    name: Push2Remote
    remoteUrl: https://github.com/superwhys/superBlog
    passwordSecret: Publish2GIthub
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
